const monacoLanguageMap={
    "Assembly": "cpp",
    "Bash": "shell",
    "Basic": "vb",
    "C (Clang)": "c",
    "C (GCC)": "c",
    "C++ (GCC)": "cpp",
    "Clojure": "clojure",
    "C#": "csharp",
    "COBOL": "plaintext",
    "Common Lisp": "scheme",
    "Dart": "dart",
    "D": "plaintext",
    "Elixir": "elixir",
    "Erlang": "erlang",
    "F#": "fsharp",
    "Fortran": "plaintext",
    "Go": "go",
    "Groovy": "groovy",
    "Haskell": "haskell",
    "Java": "java",
    "JavaScript": "javascript",
    "Kotlin": "kotlin",
    "Lua": "lua",
    "Objective-C": "objective-c",
    "OCaml": "fsharp",
    "Octave": "objective-c",
    "Pascal": "pascal",
    "Perl": "perl",
    "PHP": "php",
    "Prolog": "plaintext",
    "Python": "python",
    "R": "r",
    "Ruby": "ruby",
    "Rust": "rust",
    "Scala": "scala",
    "SQL": "sql",
    "Swift": "swift",
    "TypeScript": "typescript"
};

export default monacoLanguageMap